# Generated by Django 3.2 on 2021-05-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='eng_id',
            field=models.IntegerField(default=0),
        ),
    ]
