# Generated by Django 3.2 on 2021-05-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0002_alter_engineer_eng_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='eng_id',
            field=models.CharField(max_length=50),
        ),
    ]
