# Generated by Django 3.2 on 2021-05-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0006_auto_20210506_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remark',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
