# Generated by Django 3.2 on 2021-05-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0007_task_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
