# Generated by Django 3.2 on 2021-05-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0009_alter_task_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['cr_date']},
        ),
        migrations.AlterField(
            model_name='task',
            name='cr_project_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
