# Generated by Django 3.2 on 2021-05-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0010_auto_20210524_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='eng_department',
            field=models.CharField(default='allot', max_length=100),
            preserve_default=False,
        ),
    ]
