# Generated by Django 3.2 on 2021-05-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0011_engineer_eng_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attendance_point',
            field=models.SmallIntegerField(choices=[(0, '0'), (1, '1')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='result_point',
            field=models.SmallIntegerField(choices=[(0, '0'), (1, '1')]),
        ),
    ]
