# Generated by Django 3.2 on 2021-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0012_auto_20210526_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rollback_point',
            field=models.SmallIntegerField(blank=True, choices=[(0, '0'), (1, '1')], default='0'),
            preserve_default=False,
        ),
    ]
