# Generated by Django 3.2 on 2021-05-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0014_alter_task_rollback_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rollback_point',
            field=models.SmallIntegerField(blank=True, choices=[(0, '0'), (1, '1')], default=0, null=True),
        ),
    ]
